# Welcome {.unnumbered}

This is the course book for **LDRS 663**, and this course examines the theoretical foundations and professional practices of coaching learners in blended-learning environments with an emphasis on facilitating transformational learning experiences. The intersection of adult learning, educational technology, and international education thought is investigated in relation to the development of effective strategies for coaching learners within the emerging context of technologically distributed global higher education. Projects develop digital literacy skills, including the use of communication, collaboration and publishing tools; and media literacy, including knowledge of copyright, open licensing, and digital citizenship.

::: {.note icon="true"}

Please read the full course syllabus located on the Course Home page in Moodle. It includes key information about the course schedule, assignments, and policies. 

:::

## Course Activities

Below is some key information on features you will see throughout the course.

::: {.learning-activity}

This box will prompt you to engage in course concepts by:

- Viewing resources and reflecting on your experience and/or learning. 
- Checking your understanding to make sure you are ready for what follows. Ways to check your learning might include self-check quizzes or questions for discussion.

::: {.note}

Working through course activities will help you to meet the learning outcomes and successfully complete your assessments.

:::

:::
