# Getting Started with Obsidian {-}

One valuable tool we are going to show you is called Obsidian, a free note-taking and mind-mapping app.  Before you go through the instructions in the activity below, watch the following video [This is Obsidian](https://www.youtube.com/watch?v=d2FNqEDGc8g){target="_blank”}.




<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/d2FNqEDGc8g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 




### Activity: Getting Started with Obsidian {-}

:::{.callout}

Follow the steps below to install Obsidian on your computer.

1. Go to [obsidian.md](https://obsidian.md/download){target="_blank"} and [follow these instructions to install Obsidian on your computer.](https://help.obsidian.md/Getting+started/Download+and+install+Obsidian){target="_blank"}
    - It is recommended that you use a computer, rather than a mobile phone to install Obsidian, but please let your instructor know if you are on mobile.
    - You do NOT need to purchase any upgrades such as **Obsidian Sync** or **Obsidian Publish**.
2. Work through the **Getting Started** section of the Obsidian help pages starting with **[Create a vault](https://help.obsidian.md/Getting+started/Create+a+vault){target="_blank"}**.
    - When you create the vault in this step, we recommend that you name it **TWU** or something similar. Later, you can create as many vaults as you would like.
3. It is recommended that you [use one of the sync services listed here](https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices){target="_blank"} so that your files are backed up.   

If you are having any difficulty in installing Obsidian, feel free to reach out to each other or your instructor for support.  There are also several tutorials and videos online, so you are encouraged to seek out these resources.  One example is [Obsidian for Beginners: Start HERE — How to Use the Obsidian App for Notes](https://www.youtube.com/watch?v=QgbLb6QCK88){target="_blank"}.  The first minute shows how to set up Obsidian...and if you'd like a sneak peek at the amazing features this tool has to offer, watch on!  We'll get to these additional uses of Obsidian later in the course.

:::

Obsidian will become a backbone of this course. One of the advantages of Obsidian is that everything you do in the app happens on your own computer, rather than *the cloud*, which is just another way of saying *someone else's computer*. However, the drawback to that is that you need to ensure that you have a backup of your vaults in a secure location, either one of the sync services mentioned in step 3, above, or another backup system. 

### Activity: Download the Starter Vault {-}

:::{.callout}

To give you a head start, we have created a **starter vault** for you to download and use. Follow the instructions below to access the starter vault.

1. Download the 'Starter Obsidian Vault' from Moodle. 
    - This will download a file called `ldrs663-vault.zip` to your computer.
2. Move the file to your `Documents` folder.
3. Unzip or extract the contents of the file.
4. Rename the folder to `ldrs663-[YourName]`.
5. Open the **Obsidian** app and click the `Open another vault` icon in the bottom left corner.



6. Choose the `ldrs663-[YourName]` folder, and then Obsidian will ask you to trust this vault. Click 'Trust author and enable plugins'.
7. Once you are in the vault, feel free to take a look around. 

:::


